language: cpp
os: osx
osx_image: xcode7.3

env:
  global:
    - WX_VERSION="3.1.3"
    - LUAJIT_VERSION="2.0.5"
  matrix:
    - CONFIGURATION="Debug"
    - CONFIGURATION="Release"

install:
  # For tagged builds, use the tag name as the version.
  # Otherwise, read the version from the VERSION file.
  - if [ "$TRAVIS_TAG" != "" ]; then export XWORD_VERSION=$TRAVIS_TAG; else export XWORD_VERSION=$(cat VERSION); fi
  # Build LuaJIT
  - bash build-luajit.sh $LUAJIT_VERSION
  # Build and install wxWidgets, with our custom tweaks patch
  - ./build-wxwidgets.sh $WX_VERSION $CONFIGURATION

# Cache the compiled wxWidgets so it can be in with future builds
cache:
  directories:
    - $HOME/wxWidgets-$WX_VERSION
    - $HOME/LuaJIT-$LUAJIT_VERSION

# Run premake to create the Xcode project
before_script:
  - ./premake5 --wx-config-debug=$HOME/wxWidgets-$WX_VERSION/bin/wx-config --wx-config-release=$HOME/wxWidgets-$WX_VERSION/bin/wx-config xcode4

# Build XWord
script:
  - xcodebuild -project build/xcode4/XWord.xcodeproj -configuration "$CONFIGURATION" build

# For deployed builds, zip the .app folder
before_deploy:
  - pushd bin/$CONFIGURATION
  - zip -r XWord-macOS.zip XWord.app/ -x *.fbp -x "*/scripts/_*" -x "*/scripts/*debug*"
  - popd
  - sed -e "s/{VERSION}/${XWORD_VERSION}/" -e "s/{OS_FILE}/XWord-macOS.zip/" dist/packages_template.lua > dist/packages_mac.lua

# Deploy tagged release builds to GitHub Releases
deploy:
  provider: releases
  api_key:
    secure: TKwdr3ceZqNRBfQZPd77j+JNwtn0PNnaeI/c9Cs0oE6aYqNltCouDx9wUIPEcb8OmAaymFBuhqLOm0PgvRldSr2Z1L+DdwyDuA5fTi956ZEmZ2fPQD3IfUuTjfkmjOEEsjBWaZeqoPAddvP9xh0TzHqpBameyxUy1OiOuFky3Oc7yKF3AHtwgwVxawS64ad34eXmX/B/SfSYuC8ZPatjaYaldiRQej0PzFY2WuqHNDNlEiF0r1647h7kIOGnMIOBZMwSDhu5Ho8VwtTn6OCBlLwM3YDDGZXDjZk74a2pGb7WFg9OT88pCJcEnYhgKqYJ/Z4B0EH1e8lKeZ7idKFilBnwSc/LEv2mXtkmX+nzkvQrYgc/7CpYCFowrwi85baetJIsAAugz/Zyuukxl9+TUaiAL0LqwkCOpTodiJ1YjKexH+V6W9KXyRRatW/ybgN/4qrmMrBP0B+u+TQjbZYpNlWK1f5Qp+Esqntsm84Jo9siGwHYlWBhmK+aWXDGus/WPHWlN2D9yUr8u3rR4v0i309+T17TRADCOx12sIdFjI+9Hu0jF/r1e4Mkh8o5YwTFSb17bGoeEJOCKqyCrPTzHffAzl9JYden4CQCy46SsslJsRZTfnJ8Vh2J3C5mH9KHZyb9uUEPUDyM0Mq02ELR6s1xIsRPZCdGTr2lPl+eZyU=
  file:
    - bin/$CONFIGURATION/XWord-macOS.zip
    - dist/packages_mac.lua
  skip_cleanup: true
  on:
    tags: true
    condition: $CONFIGURATION = "Release"
